---
  - name: Ensure port is routed
    command: "vtysh -c 'config terminal' -c 'interface {{ item.name }}' -c 'routing'"
    with_items: "{{switches[hostvars[inventory_hostname].inventory_hostname].interfaces}}"
    when: item.name != "lo1"

  - name: Touch loopback
    command: "vtysh -c 'config terminal' -c 'interface loopback 1'"

  - name: Prepare port JSON templates
    template:
      src: ports.json.j2
      dest: ./hostname_{{ hostvars[inventory_hostname].inventory_hostname }}.json
    delegate_to: 127.0.0.1

  - name: Ensure port L3 interface is configured and port is up
    ops_template:
      host: localhost
      transport: rest
      validate_certs: False
      src: ./hostname_{{ hostvars[inventory_hostname].inventory_hostname }}.json
      username: root
      password:

  - name: Remove temporaly templates
    file:
      path: ./hostname_{{ hostvars[inventory_hostname].inventory_hostname }}.json
      state: absent
    delegate_to: 127.0.0.1
